name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: '92744802'
        token: 1573926362:AAFJXQSLUdekBf83ima6mgZqn2zLSBDkOoo
        args: The ${{ github.event_name }} event triggered first step.
